version: "3.4"
services:
  ttapp-frontend:
    stdin_open: true
    image: ttapp-frontend:latest
    environment:
      - REACT_APP_BASE_URL=${REACT_APP_BASE_URL}
    expose:
      - 8080
    ports:
      - 8080:80
    environment:
      - CHOKIDAR_USEPOLLING=true
