version: "3.4"
services:
  react-nginx-app:
    stdin_open: true
    image: ttapp-frontend:latest
    expose:
      - 8080
    ports:
      - 8080:80
    environment:
      - CHOKIDAR_USEPOLLING=true
